Added: body-build-files, build-files, etc.

diff --git a/bin/dum_dum_nodejs b/bin/dum_dum_nodejs
--- a/bin/dum_dum_nodejs
+++ b/bin/dum_dum_nodejs
@@ -31,28 +31,56 @@ case $action in
     bash_setup print_help $0
     ;;
 
-
   upgrade)
     # === upgrade
     cd "$THIS_DIR"
     js_setup upgrade
     ;;
 
-  body-files)
-    # === __ body-files  "main/dir"
-    dir="$1"; shift
+  prepend-to)
+    name="$1"; shift
+    text="$@"
+    [[ -z "$text" ]] && echo '!!! Text is missing.' 1>&2 && exit 1 || :
+    for FILE in $($0 body-build-files $name); do
+      new_content="$text\n$(cat "$FILE")"
+      echo -e "$new_content" > "$FILE"
+      echo "=== $FILE"
+    done
+    ;;
+
+  jshint)
+    # === __ jshint
+    for FILE in $($0 build-files node); do
+      js_setup jshint "$FILE"
+    done
+    ;;
+
+  body-build-files)
+    # === __ body-build-files  [dom|node|etc.]
+    name="$1"; shift
+    dir="main/$name"
     find "$dir" -type f -iname "_.*.js" -prune -o -iname "*.js" -print
     ;;
 
+  build-files)
+    # === __ build-files  [dom|node|etc.]
+    name="$1"; shift
+    dir="main/$name"
+    touch $dir/_.top.js
+    touch $dir/_.bottom.js
+    echo "$dir/_.top.js" $($0 body-build-files $name) "$dir/_.bottom.js"
+    ;;
+
   build-node)
-    $0 duplicate_functions || { stat="$?"; echo "!!! Dup found." 1>&2; exit $stat; }
     # === __  build-node
-    touch main/node/_.top.js
-    touch main/node/_.bottom.js
-    dir="main/node"
     output="build"
-    files="$($0 body-files "$dir")"
-    uglifyjs "$dir/_.top.js" $files "$dir/_.bottom.js"  --source-map "$output/node.js.map" > "$output/node.js"
+    file="$output/node.js"
+    uglifyjs                  \
+      $($0 build-files specs) \
+      $($0 build-files base)  \
+      $($0 build-files node)  \
+      --source-map "$output/node.js.map" > "$file"
+    echo "$file"
     ;;
 
   function_name)
@@ -155,10 +183,7 @@ case $action in
     ;;
 
   test)
-    if $0 duplicate_functions; then
-      echo "!!! Duplicate functions found." 1>&2
-      exit 1
-    fi
+    $0 duplicate_functions || { stat="$?"; echo "!!! Dup found." 1>&2; exit $stat; }
     target=""
     if [[ -n "$@" ]]; then
       target="$1"; shift
