Touchups.

diff --git a/bin/dum_dum_html b/bin/dum_dum_html
--- a/bin/dum_dum_html
+++ b/bin/dum_dum_html
@@ -61,6 +61,7 @@ case $action in
 
   test)
     if [[ -z "$@" ]]; then
+      js_setup jshint main/main.js
       find specs/ -maxdepth 1 -mindepth 1 -type d | xargs -I DIR $0 test DIR
       exit 0
     fi
@@ -76,9 +77,13 @@ case $action in
         rm -rf "$ACTUAL"; mkdir -p "$ACTUAL"
 
         EXPECT="$DIR/expect"
-        { $0 "$FILE" "$ACTUAL"; tput cuu1; tput el; echo -e "=== ${Green}$DIR${Color_Off}"; } || { stat=$?; echo -e "=== ${Red}Failed${Color_Off} ($stat)"; }
+        { $0 "$FILE" "$ACTUAL" "$TEMP"; } || { stat=$?; echo -e "=== ${Red}Failed${Color_Off} ($stat)"; exit $?; }
         if ! bash_setup dirs-are-equal "$ACTUAL" "$EXPECT"; then
+          echo -e "=== ${Red}Failed${Color_Off}"
           exit 1
+        else
+          tput cuu1; tput el
+          echo -e "=== ${Green}$DIR${Color_Off}"
         fi
       done
 
@@ -117,7 +122,7 @@ case $action in
 
       if [[ "$path" == main/*.js ]]; then
         if [[ "$path" == main/main.js ]]; then
-          { js_setup jshint "$path" && $0 test; } || :
+          $0 test || :
         else
           js_setup jshint "$path" || :
         fi
