Added: continue testing from last failed test.

diff --git a/bin/dum_dum_html b/bin/dum_dum_html
--- a/bin/dum_dum_html
+++ b/bin/dum_dum_html
@@ -69,10 +69,21 @@ case $action in
   test)
     # === __   test
     # ==  __   spec/dir
+    if [[ ! -e "$TEMP/last_failed" ]]; then
+      last_failed=""
+    else
+      last_failed="$(cat "$TEMP/last_failed")"
+    fi
+
     if [[ -z "$@" ]]; then
       js_setup jshint main/main.js
       while read DIR; do
-        $0 test "$DIR"
+        if [[ -n "$last_failed" && "$last_failed" != "$DIR" ]]; then
+          continue
+        else
+          last_failed=""
+        fi
+        $0 test "$DIR" || { stat="$?"; echo "$DIR" >> "$TEMP/last_failed"; exit $stat; }
       done < <(find specs/ -maxdepth 1 -mindepth 1 -type d)
       exit 0
     fi
