Added: nesting of templates.

diff --git a/bin/dum_dum_html b/bin/dum_dum_html
--- a/bin/dum_dum_html
+++ b/bin/dum_dum_html
@@ -36,11 +36,11 @@ case $action in
     ;;
 
   watch)
+    bash_setup is_same_file "$0" || :
     # === watch
     cmd () {
       path="$1"; shift
-      bash_setup is_same_file "$path"
-      js_setup   jshint       "$path"
+      js_setup   jshint "$path" && { bash_setup is_same_file "$path" || : ; }
     }
 
     failed=""
@@ -107,7 +107,7 @@ case $action in
       cat "$FILE" | head -n $((split_on - 1)) > "$TEMP"
       actual="$($0 $TEMP)"
       if [[ "$actual" != "$expect" ]]; then
-        echo "=== Failed: $FILE" 1>&2
+        echo -e "=== Failed: ${Red}${FILE}${Color_Off}" 1>&2
         diff <(echo "$actual") <(echo "$expect")
         exit 1
       fi
